Update sidb_prepare_config.yaml

diff --git a/sidb_prepare_config.yaml b/sidb_prepare_config.yaml
--- a/sidb_prepare_config.yaml
+++ b/sidb_prepare_config.yaml
@@ -39,4 +39,4 @@ data:
      select * from dual; 
      exit; 
      EOF 
-     if [ $? -eq 0 ] ; then echo "connect successful" ; else echo "DB connect failed, waiting 2 mins and exiting..." ; sleep 120 ; exit 5 ; fi 
+     if [ $? -eq 0 ] ; then echo "connect successful" ; else echo "DB connect failed, waiting 3 mins and exiting..." ; sleep 180 ; exit 5 ; fi 
